import { Inter } from 'next/font/google'
import "./globals.css";
import Layout from '@/component/Layout';
import { ContextProdiver } from '@/context/ContextMenu';


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <body className={inter.variable}>
        <ContextProdiver>
          <Layout>
            {children}
          </Layout>
        </ContextProdiver>
      </body>
    </html>
  );
}
